### ISSUE TITLE
Port to RDF4J

### ISSUE THREAD

**Issue by bjonnh** [Nanopublication/nanopub-java#3]
As sesame is now called RDF4J, what about porting it to the last version?

**Comment by tkuhn** [comment]
Yes, I should do this at some point. I probably have to port `trustyuri` first to make them compatible.

Do you need this urgently for using this library? I can try to prioritize it...

**Comment by bjonnh** [comment]
No emergency don't worry.

**Comment by tkuhn** [comment]
RDF4J migration is done: cd430d1af107a6f0334e84899a8d9c479459e5a7

Still needs more testing, and I have to update the Maven artifact too. I hope it works as expected.

**Comment by tkuhn** [comment]
It requires a local installation of the latest trusturi-java version at the moment, which is not yet on Maven Central either.

**Comment by tkuhn** [comment]
And now also on Maven Central: http://central.maven.org/maven2/org/nanopub/nanopub/1.19/
