### ISSUE TITLE
Nanopub head currently needs to come first

### ISSUE THREAD

**Issue by raar1** [Nanopublication/nanopub-java#5]
Python libraries like rdflib will generally output quads in any order they like. However, "np check" (and at least some other np functions like "np mktrusty" etc) require the `:head` context quads to come first.

For example:

Valid nanopub (according to `np check`:
```
@prefix : <http://example.org/pub1#> .
@prefix ex: <http://example.org/> .
@prefix np:  <http://www.nanopub.org/nschema#> .
@prefix prov: <http://www.w3.org/ns/prov#> .
@prefix xsd:  <http://www.w3.org/2001/XMLSchema#> .
:head {
    ex:pub1 a np:Nanopublication .
    ex:pub1 np:hasAssertion :assertion .
    ex:pub1 np:hasProvenance :provenance .
    ex:pub1 np:hasPublicationInfo :pubInfo .
}
:assertion {
    ex:trastuzumab ex:is-indicated-for ex:breast-cancer .
}
:provenance {
    :assertion prov:generatedAtTime "2012-02-03T14:38:00Z"^^xsd:dateTime .
    :assertion prov:wasDerivedFrom :experiment .
    :assertion prov:wasAttributedTo :experimentScientist .
}
:pubInfo {
    ex:pub1 prov:wasAttributedTo ex:paul .
    ex:pub1 prov:generatedAtTime "2012-10-26T12:45:00Z"^^xsd:dateTime .
}
```

Not valid (:head is at the bottom):
```
@prefix : <http://example.org/pub1#> .
@prefix ex: <http://example.org/> .
@prefix np:  <http://www.nanopub.org/nschema#> .
@prefix prov: <http://www.w3.org/ns/prov#> .
@prefix xsd:  <http://www.w3.org/2001/XMLSchema#> .
:assertion {
    ex:trastuzumab ex:is-indicated-for ex:breast-cancer .
}
:provenance {
    :assertion prov:generatedAtTime "2012-02-03T14:38:00Z"^^xsd:dateTime .
    :assertion prov:wasDerivedFrom :experiment .
    :assertion prov:wasAttributedTo :experimentScientist .
}
:pubInfo {
    ex:pub1 prov:wasAttributedTo ex:paul .
    ex:pub1 prov:generatedAtTime "2012-10-26T12:45:00Z"^^xsd:dateTime .
}
:head {
    ex:pub1 a np:Nanopublication .
    ex:pub1 np:hasAssertion :assertion .
    ex:pub1 np:hasProvenance :provenance .
    ex:pub1 np:hasPublicationInfo :pubInfo .
}
```

**Comment by tkuhn** [comment]
I just checked the code. This is actually correctly handled in NanopubImpl, which expects just one nanopub. But in MultiNanopubRdfHandler, which expects a stream of nanopubs, it is assumed that the head graph comes first, for practical reasons.

I could add an option like "-1" to force the use for NanopubImpl for operations that can otherwise also deal with streams. Or improve MultiNanopubRdfHandler, but this is a bit harder.

Depends on how important this is? :)

**Comment by raar1** [comment]
It's not super important, but libraries like rdflib don't allow sorting of the serialized output. I currently have a rather ugly hack for cutting the head graph from the trig output and moving it to be first after the @prefix lines. But that will hold for now, so it's not urgent. I might have a look at MultiNanopubRdfHandler at some point and see if I can see an easier fix.

**Comment by tkuhn** [comment]
I managed to fix this! In fact, the existing code was much too complicated and much simpler code solves the problem :)

This is the commit: https://github.com/Nanopublication/nanopub-java/commit/a72d3530c64c04d7146a8ffb1ebc36be71573054

I will publish a new release as soon as I get to it. Until then, you can build your own jar file with `mvn package` and then run it with the `java -jar ...` command.

The triples of a nanopublication can now be in an arbitrary order, but nanopublications have to come one after the other in a stream of nanopublications. So, you can't start with all head graphs and then all assertion graphs etc. for a file with several nanopubs. But as long as all the triples of a nanopub are together, their order no longer matters.

**Comment by raar1** [comment]
That's great, thanks! The nanopublications I produce will always be one after another, so no worries there.

**Comment by tkuhn** [comment]
New release published. If you use the `np` script, just deleting the jar file will make sure the new one is downloaded on the next run of `np`. I hope everything is working now as expected.

**Comment by raar1** [comment]
Yep, thanks! Tested with :Head at the end of the .trig and now validates with ```np check```.
